/**
 * ============================================================================
 *  ORGANIZATION CONFIG — CBS Certificate Portal
 * ============================================================================
 *  This file holds settings shared by EVERY workshop (organization name,
 *  site copy, ID formatting rules, and the default certificate layout).
 *
 *  Workshop-specific details — name, code, date, template artwork, and
 *  per-template layout — live in a separate registry:
 *
 *      👉  config/workshops.ts  👈
 *
 *  To add a new workshop, you do NOT edit this file. Go to
 *  config/workshops.ts and add one entry to the WORKSHOPS array.
 * ============================================================================
 */

// ---------------------------------------------------------------------------
// 1. ORGANIZATION / SITE-WIDE BRANDING
// ---------------------------------------------------------------------------
export const ORG_CONFIG = {
  /** Organization running every workshop on this portal */
  organizationName: "Character Building Society",
  organizationAbbreviation: "CBS",

  /** Institution the organization belongs to */
  institutionName: "Muhammad Nawaz Sharif University of Agriculture, Multan",
  institutionAbbreviation: "MNSUAM",

  /** Homepage copy (shown regardless of which workshop a certificate is for) */
  siteTitle: "Certificate Download Portal",
  siteTagline:
    "Enter your Certificate ID to instantly generate, preview, and download your official Certificate of Participation.",

  /**
   * Canonical production URL — used ONLY for page metadata (Open Graph /
   * social link previews). QR codes on certificates always encode the
   * live browser origin at generation time, so verification works
   * correctly even if you forget to update this. Update it after your
   * first deploy for nicer link-preview cards when the URL is shared.
   */
  siteUrl: "https://cbs-certificate-portal.vercel.app",
} as const;

// ---------------------------------------------------------------------------
// 2. CERTIFICATE ID FORMAT
// ---------------------------------------------------------------------------
/** How many digits the sequence number is zero-padded to, e.g. 3 -> "005". */
export const CERTIFICATE_ID_PAD_LENGTH = 3;

// ---------------------------------------------------------------------------
// 3. SITE-WIDE ASSET PATHS
// ---------------------------------------------------------------------------
export const ASSET_PATHS = {
  /** Standalone organization logo (square, used in-app: header, favicon source) */
  logo: "/cbs-logo.png",
} as const;

// ---------------------------------------------------------------------------
// 4. OUTPUT DIMENSIONS — shared by every workshop's certificate
// ---------------------------------------------------------------------------
/** Source templates' native pixel dimensions. If a new workshop's artwork
 *  is a different size, its own LayoutConfig ratios still work (ratios are
 *  resolution-independent) but update this if you rely on it elsewhere. */
export const TEMPLATE_PIXEL_SIZE = { width: 1448, height: 1086 };

/** Output PDF/PNG page size, in points/px-equivalent units. 12in x 9in
 *  preserves the default template's exact 4:3 aspect ratio (1448:1086 =
 *  12:9), so the artwork is never stretched or letterboxed. */
export const PAGE_WIDTH_PT = 864; // 12in @ 72pt/in
export const PAGE_HEIGHT_PT = 648; // 9in @ 72pt/in

// ---------------------------------------------------------------------------
// 5. DEFAULT TEMPLATE LAYOUT
// ---------------------------------------------------------------------------
/**
 * Geometry for the "Laptop Survival Workshop" template design — reused as
 * the default for any new workshop whose artwork keeps the same
 * placeholder positions. Every new WORKSHOPS entry in config/workshops.ts
 * can either reuse this object directly, or define its own if the new
 * template's placeholders sit in different spots.
 *
 * HOW THESE NUMBERS WERE DERIVED
 * The template (1448 x 1086 px) was scanned for dark-pixel clusters
 * (grayscale threshold < 100) to get exact bounding boxes for the
 * "<<Full Name>>" and "ID: <<ID>>" placeholders, then converted to
 * *ratios* (0–1) of image width/height so the same config works at any
 * output resolution.
 *
 * Measured pixel boxes (for reference / future re-tuning):
 *   "<<Full Name>>"  -> x: 490–932,  y: 510–553   (center 711, 531.5)
 *   "ID: <<ID>>"     -> x: 860–964,  y: 883–895   (widened below to fit
 *                        the longer "CBS-LSW-2026-001" format)
 *   QR code          -> placed in a hand-picked blank region (measured
 *                        via pixel-density scan) at x:1190–1320, y:275–405
 *
 * Sampled colors:
 *   Name text  -> pure black (#000000)
 *   ID text    -> dark navy  (#002352)
 *   Background near placeholders -> near-white (~#f9f9f9)
 */
export const DEFAULT_LAYOUT_CONFIG = {
  /** Full Name placeholder */
  nameField: {
    centerXRatio: 0.491,
    centerYRatio: 0.4894,
    maskBox: {
      leftRatio: 0.3177,
      rightRatio: 0.6699,
      topRatio: 0.4586,
      bottomRatio: 0.5212,
    },
    font: "serif" as const, // maps to TimesRoman (PDF) / Times New Roman (canvas)
    color: "#000000",
    maxFontSize: 40,
    minFontSize: 16,
    maxWidthRatio: 0.62, // auto-shrinks long names to fit this fraction of page width
  },

  /** Certificate ID (e.g. "ID: CBS-LSW-2026-001"), left-aligned */
  idField: {
    startXRatio: 0.5939,
    centerYRatio: 0.8186,
    maskBox: {
      leftRatio: 0.5836,
      rightRatio: 0.777,
      topRatio: 0.8039,
      bottomRatio: 0.8315,
    },
    font: "sans-bold" as const, // maps to HelveticaBold (PDF) / Arial Bold (canvas)
    color: "#002352",
    label: "ID: ",
    maxFontSize: 15,
    minFontSize: 8,
    maxWidthRatio: 0.185, // auto-shrinks to fit the widened ID box
  },

  /** Verification QR code, placed in a blank area of the template */
  qrField: {
    box: {
      leftRatio: 0.8219,
      rightRatio: 0.9116,
      topRatio: 0.2533,
      bottomRatio: 0.373,
    },
    caption: "SCAN TO VERIFY",
    captionCenterXRatio: 0.8667,
    captionCenterYRatio: 0.3859,
    captionFontSize: 8.5,
    captionColor: "#0b1c47",
  },

  /** Off-white fill used to mask over the original placeholder text,
   *  sampled directly from the template background. */
  maskColor: "#f9f9f9",
} as const;
